/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef chat_CONSTANTS_H
#define chat_CONSTANTS_H

#include "chat_types.h"

namespace chat {

class chatConstants {
 public:
  chatConstants();

};

extern const chatConstants g_chat_constants;

} // namespace

#endif
